FROM ubuntu:20.04
LABEL maintainer="marcusvbrangel"
RUN apt update && \
    apt install nginx -y && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /var/www/html/
COPY index.html .
ENV APP_VERSION 1.0.0
EXPOSE 80
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
